#
# This file contains configuration flags to customize your site
#

# Site locale
lang: "id"

# Name of your site (displayed in the header)
title: Rully Pratama

# Short bio or description (displayed in the header)
description: Another random thought

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/me-logo.png

#
# Flags below are optional
#

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://www.rullypratama.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Navigation menu
navigation_links:
  - title: Blog
    url: /

  - title: About
    url: /about

  - title: Search
    url: /search

# Includes an icon in the footer for each username you enter
footer-links:
  email: hello@rullypratama.com
  instagram: rullypratamaa
  linkedin: rullypratama
  twitter: rullyypratamaa
  
# Time zone
timezone: Asia/Jakarta

# Excerpt separator
excerpt_separator: <!--more-->

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: rpratama123

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Jekyll-seo-tag properties

twitter:
  username: rullyypratamaa
  card: summary_large_image

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plug-ins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag # Add metadata tags for search engines and social networks
  - jekyll-gist
  - jekyll-paginate
  - jemoji
  - webrick
  - jekyll-github-metadata

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME